language: php

php:
  - 7.3

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --prefer-source --no-interaction
  - COMPOSER_MEMORY_LIMIT=-1 travis_retry composer require php-coveralls/php-coveralls
  - cp .env.example .env
  - php artisan key:generate
  - php artisan storage:link

script:
  - vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_success:
  - vendor/bin/php-coveralls -v --exclude-no-stmt